Best/Models/BestContext.cs
using Microsoft.EntityFrameworkCore;

namespace Best.Models
{
    public class BestContext : DbContext
    {

        public virtual DbSet<Restaurant> Restaurants { get; set; }
        public DbSet<Cuisine> Cuisines { get; set; }

        public BestContext(DbContextOptions options) : base(options) { }

    }
}

Best/Models/Cuisine.cs
using System.Collections.Generic; //maybe unnecessary?

namespace Best.Models
{
    public class Cuisine
    {
        public string Name { get; set; }
        public int CuisineId { get; set; }
        // public virtual ICollection<Cuisine> Cuisines { get; set; } //this is not necessary?
        public int RestaurantId { get; set; }
        public virtual Restaurant Restaurant { get; set; }
    }
}

Best/Models/Restaurant.cs
using System.Collections.Generic;

namespace Best.Models
{
    public class Restaurant
    {
        public Restaurant()
        {
            this.Cuisines = new HashSet<Cuisine>();
        }

        public int RestaurantId { get; set; }
        public string Name { get; set; }
        public virtual ICollection<Cuisine> Cuisines { get; set; }
    }
}

Best/Controllers/CuisineController.cs
using Microsoft.AspNetCore.Mvc;
using Best.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Best.Controllers
{
    public class CuisineController:Controller
    {
        private readonly BestContext _db;
        public CuisineController(BestContext db)
        {
            _db = db;
        }

        //Cuisine Create: displays a form to make a new cuisine
        public ActionResult Create(int id)
        {
            //find the restaurant from DB
            //pass in as model
            ViewBag.RestaurantId = id;
            return View();
        }

        //Cuisine Create Post: Accepts new cuisine object from form, adds it to database, and redirects to Restaurant Details page
        [HttpPost]
        public ActionResult Create(Cuisine cuisines)
        {
            _db.Cuisines.Add(cuisines);
            _db.SaveChanges();
            return RedirectToAction("Details", "Restaurant", new { id = cuisines.RestaurantId });
        }
    }
}

Best/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace Best.Controllers
{
    public class HomeController : Controller
    {

        [HttpGet("/")]
        public ActionResult Index()
        {
            return View();
        }

    }
}

Best/Controllers/RestaurantController.cs
using Microsoft.AspNetCore.Mvc;
using Best.Models;
using System.Collections.Generic;
using System.Linq;
using Microsoft.EntityFrameworkCore;

namespace Best.Controllers
{
    public class RestaurantController : Controller
    {
        private readonly BestContext _db;

        public RestaurantController(BestContext db)
        {
            _db = db;
        }

        //Restaurant Index: displays list of restaurants in the database
        public ActionResult Index()
        {
            List<Restaurant> model = _db.Restaurants.ToList();
            return View(model);
        }

        //Restaurant Create: displays a form to make a new restaurant
        public ActionResult Create()
        {
            return View();
        }

        //Restaurant Create Post: Accepts new restaurant object, adds it to database, and redirects to Restaurant Index
        [HttpPost]
        public ActionResult Create(Restaurant restaurants) //the parameter name "restaurants" refers to the actual table in the database, so it must have the same name as the table otherwise it will yell at you.
        {
            _db.Restaurants.Add(restaurants);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Restaurant Details: displays list of cuisines for a particular restaurant ("int id" parameter refers to the restaurant's ID)
        public ActionResult Details(int id)
        {
            Restaurant thisRestaurant = _db.Restaurants.Include(restaurant => restaurant.Cuisines).FirstOrDefault(rest=> rest.RestaurantId == id); //Need the "Include" portion in order to force the page to re-load the restaurant's Cuisines list, otherwise the cuisine you just added to it won't show up.
            return View(thisRestaurant);
        }

        //Restaurant Delete: displays a confirmation page for the restaurant you want to delete
        public ActionResult Delete(int id)
        {
            var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
            return View(thisRestaurant);
        }

        //Restaurant Delete Post: deletes restaurant from the database and redirects to Restaurant Index
        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {
            var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
            _db.Restaurants.Remove(thisRestaurant);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        //Restaurant Edit: displays a page where the user can edit the restaurant's details
        public ActionResult Edit(int id)
        {
            var thisRestaurant = _db.Restaurants.FirstOrDefault(restaurant => restaurant.RestaurantId == id);
            return View(thisRestaurant);
        }

        //Restaurant Edit Post: edits the restaurant's details and redirects to Restaurant Index
        [HttpPost]
        public ActionResult Edit(Restaurant restaurant)
        {
            _db.Entry(restaurant).State = EntityState.Modified;
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

Best/Views/Cuisine/Create.cshtml
@{
  Layout = "_Layout";
}

@model Best.Models.Cuisine

<h2>Add a cuisine<h2>
@using (Html.BeginForm())
{
    @*<p>Restaurant Id: @ViewBag.RestaurantId</p>*@
    <input type="hidden" name="RestaurantId" value=@ViewBag.RestaurantId /> //Name attribute needs to EXACTLY match the name of the property (in this case, the RestaurantId property of the Cuisine class) in order to bind the value correctly upon creating the child (Cuisine) object!!!
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new { @class="form-control"})
    <input type="submit" value="Add new type" class="btn btn-default" />
}

<button class="btn btn-default">@Html.ActionLink("Back To Restaurant", "Details", "Restaurant", new { id = ViewBag.RestaurantId })</button>                                  

Best/Views/Home/Index.cshtml
@{
  Layout = "_Layout";
}

<h1>Best places to eat around town</h1>
<hr>
<button class="btn btn-default">@Html.ActionLink("See Restaurants", "Index", "Restaurant")</button>
   

Best/Views/Restaurant/Create.cshtml
@{
  Layout = "_Layout";
}

@model Best.Models.Restaurant
<h1>Add a Restaurant</h1>

@using (Html.BeginForm())
{
    @Html.LabelFor(model => model.Name)
    @Html.TextBoxFor(model => model.Name, new { @class="form-control"})

    <input type="submit" value="Add a new restaurant" class="btn btn-default"/>
}

<button class="btn btn-default">@Html.ActionLink("Back to list", "Index", "Restaurant")</button>

Best/Views/Restaurant/Delete.cshtml
@{
  Layout = "_Layout";
}

@model Best.Models.Restaurant

<h2>Are you <em>sure</em> you want to delete @Model.Name?</h2>

@using (Html.BeginForm())
{
    <input type="submit" value="Yes, delete it" class="btn btn-default" />
}

<button class="btn btn-default">@Html.ActionLink("No, back to restaurant", "Details", "Restaurant", new { id = @Model.RestaurantId })</button>

Best/Views/Restaurant/Details.cshtml
@{
  Layout = "_Layout";
}

@model Best.Models.Restaurant
@using Best.Models

<h2>@Model.Name</h2>
<hr />
<h3>Cuisines available at this restaurant:</h3>
@if(Model.Cuisines.Count == 0)
{
    <p>No cuisines have been added yet!</p>
}
<ul>
@foreach(Cuisine cuisine in @Model.Cuisines)
{
    <li><h3>@cuisine.Name<h3></li>
}
</ul>

<button class="btn btn-default">@Html.ActionLink("Add cuisine to the list", "Create", "Cuisine", new { id = Model.RestaurantId })</button>

<button class="btn btn-default">@Html.ActionLink("Edit this restaurant", "Edit", new { id = Model.RestaurantId })</button>

<button class="btn btn-default">@Html.ActionLink("Delete this restaurant", "Delete", new { id = Model.RestaurantId })</button>

<button class="btn btn-default">@Html.ActionLink("Back to list", "Index")</button>

Best/Views/Restaurant/Edit.cshtml
@{
  Layout = "_Layout";
}

@model Best.Models.Restaurant

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.HiddenFor(model => model.RestaurantId)

    @Html.LabelFor(model => model.Name)
    @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })

    <input type="submit" value="Save" class="btn btn-default"/>
}

<button class="btn btn-default">@Html.ActionLink("Back to restaurant", "Details", "Restaurant", new { id = @Model.RestaurantId })</button>

<button class="btn btn-default">@Html.ActionLink("See full restaurants list", "Index")</button>

Best/Views/Restaurant/Index.cshtml
@{
  Layout = "_Layout";
}

@using Best.Models;
@model List<Best.Models.Restaurant>;

<h1>Restaurants</h1>

@if (@Model.Count == 0)
{
  <h3>No restaurants have been added yet!</h3>
} 

@foreach (Restaurant restaurant in Model)
{
  <li>@Html.ActionLink($"{restaurant.Name}", "Details", new { id = restaurant.RestaurantId })</li>
}

<button class="btn btn-default">@Html.ActionLink("Add new Restaurant", "Create")</button>
<button class="btn btn-default">@Html.ActionLink("Home", "Index", "Home")</button>

Best/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Restaurants</title>
    <link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css'>
    <link rel="stylesheet" href="~/css/styles.css" />
  </head>
  <body>
    <div class="container">
        @RenderBody()
    </div>
  </body>
</html>